/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lukuvinkkikirjasto;

import java.util.Scanner;

import lukuvinkkikirjasto.ui.UserInterface;

public class Main {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Main().getGreeting());
        Scanner reader = new Scanner(System.in);
        UserInterface ui = new UserInterface(reader);
        ui.start();
    }
}
