/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lukuvinkkikirjasto;

import org.junit.*;

import lukuvinkkikirjasto.ui.IO;
import lukuvinkkikirjasto.ui.Unknown;

import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

public class UnknownTest {

    IO io;
    Unknown unknown;

    @Before
	public void setUp() {
        io = mock(IO.class);
        unknown = new Unknown(io);
    }

    @Test
    public void printsRightMessage() {
        unknown.execute();
        verify(io).output("Command not found"); 
    }

    //@After
    //public void cleanUp() {
    //    io.input()
    //}
}
